name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deployment: [
          "local",
          "docker",
        ]
        api: [
          "app",
          "cli",
        ]
        execution-mode: [
          "async",
          "sequential",
        ]
        exclude:
          # at this point, the docker container we are building runs the app only (not the cli)
          # if we want to build a version of the container that runs the cli at a later point,
          # we can do that, but for now, we are only testing the app in the container
          - deployment: "docker"
            api: "cli"

    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
      # 'local' deployment test -------------------------------------------------------------------
      - name: Test
        if: matrix.deployment == 'local'
        run: pixi run --manifest-path pixi.toml -e default pytest-${{ matrix.api }} ${{ matrix.execution-mode }}
      # 'docker' deployment test ------------------------------------------------------------------
      - name: Docker build + run
        if: matrix.deployment == 'docker'
        run: |
          pixi run --manifest-path pixi.toml docker-build
          pixi run --manifest-path pixi.toml docker-run
          sleep 5
          docker ps
      - name: Invoke container with curl
        if: matrix.deployment == 'docker'
        run:  pixi run --manifest-path pixi.toml curl-invoke ${{ matrix.execution-mode }}
